### ISSUE TITLE
Can you add docker support for arm?

### ISSUE THREAD

**Issue by filipton** [midarrlabs/midarr-server#1]
It will be really nice if you can make a docker image for arm processors.

**Comment by akashkj** [comment]
+1

**Comment by trueChazza** [comment]
> instead of just adding `arm` images, please consider building multi-arch images via [`buildx`](https://github.com/docker/buildx):
> 
> * the implementation is fairly well described in the official docs (https://docs.docker.com/desktop/multi-arch/);
> * there's a gh action for automated builds with buildx (https://github.com/docker/setup-buildx-action) that you can add to the existing workflow.

Thanks 😊

**Comment by filipton** [comment]
And I think there will be an issue with PostgreSQL image. (bitnami/postgresql isn't supported by arm)

**Comment by trueChazza** [comment]
`ghcr.io/midarrlabs/midarr-server:multi-arch`

There is now a multi-arch tagged image.
If you want to give it a test run first, before I merge into `latest`

**Comment by trueChazza** [comment]
> And I think there will be an issue with PostgreSQL image. (bitnami/postgresql isn't supported by arm)

You'll need to configure an arm compatible image.

**Comment by trueChazza** [comment]
`ghcr.io/midarrlabs/midarr-server:multi-arch`

Supports architectures:
* linux/amd64
* linux/arm64
* linux/arm/v7

**Comment by cgomesu** [comment]
> `ghcr.io/midarrlabs/midarr-server:multi-arch`
> 
> Supports architectures:
> 
>     * linux/amd64
> 
>     * linux/arm64
> 
>     * linux/arm/v7

I'll give it a try over the weekend.

**Comment by filipton** [comment]
I tried, and it's working!

My docker-compose file (with other postgres image):

```
version: '2.1'

volumes:
  database-data:

services:
  midarr:
    image: ghcr.io/midarrlabs/midarr-server:multi-arch
    ports:
      - 4000:4000
    volumes:
      - /mnt/gdrive/Movies:/movies
      - /mnt/gdrive/tvseries:/shows
    environment:
      - DB_USERNAME=my_user
      - DB_PASSWORD=my_password
      - DB_DATABASE=my_database
      - DB_HOSTNAME=postgresql
      - SETUP_ADMIN_EMAIL=admin@email.com
      - SETUP_ADMIN_NAME=admin
      - SETUP_ADMIN_PASSWORD=passwordpassword
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    image: postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=my_database
    healthcheck:
      test: "exit 0"
```
