### ISSUE TITLE
Unable to play media on latest v3 beta

### ISSUE THREAD

**Issue by onedr0p** [midarrlabs/midarr-server#310]
Hi again 👋🏼 

I currently have Midarr, Radarr and Sonarr deployed in Kubernetes, my configuration for Midarr, Radarr and Sonarr mount the same folders. Ignoring Postgresql, a translation to docker-compose would look like this:

```yaml
  midarr:
    container_name: midarr
    image: ghcr.io/midarrlabs/midarr-server:v3.0.0-beta.2
    ports:
      - 4000:4000
    volumes:
      - /eros/Media:/media:ro

  radarr:
    container_name: radarr
    image: linuxserver/radarr:version-4.1.0.6175
    ports:
      - 7878:7878
    volumes:
      - /eros/Media:/media

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:version-3.0.9.1549
    ports:
      - 8989:8989
    volumes:
      - /eros/Media:/media
```

I am unable to play media because Midarr is not looking in the right place. It should be looking in `/media/Library` not `/movies/Library`. I am actually confused how Midarr got that path to begin with.

I thought Midarr was able to pick up the media paths from querying Radarr or Sonarr? IIRC back in v1 it was working this way.

```
midarr-89fd57b5b-s89r7 midarr Server: midarr.devbu.io:80 (http)
midarr-89fd57b5b-s89r7 midarr Request: GET /movies/8073/watch
midarr-89fd57b5b-s89r7 midarr ** (exit) an exception was raised:
midarr-89fd57b5b-s89r7 midarr     ** (File.Error) could not list directory "/movies/Library": no such file or directory
midarr-89fd57b5b-s89r7 midarr         (elixir 1.14.3) lib/file.ex:1637: File.ls!/1
midarr-89fd57b5b-s89r7 midarr         (media_server 3.0.0) lib/media_server/subtitles.ex:15: MediaServer.Subtitles.get_subtitle/2
midarr-89fd57b5b-s89r7 midarr         (media_server 3.0.0) lib/media_server/subtitles.ex:22: MediaServer.Subtitles.has_subtitle/2
midarr-89fd57b5b-s89r7 midarr         (media_server 3.0.0) lib/media_server_web/live/watch_movie_live/show.html.heex:18: anonymous fn/2 in MediaServerWeb.WatchMovieLive.Show.render/1
midarr-89fd57b5b-s89r7 midarr         (phoenix_live_view 0.18.17) lib/phoenix_live_view/diff.ex:398: Phoenix.LiveView.Diff.traverse/7
midarr-89fd57b5b-s89r7 midarr         (phoenix_live_view 0.18.17) lib/phoenix_live_view/diff.ex:544: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
midarr-89fd57b5b-s89r7 midarr         (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
midarr-89fd57b5b-s89r7 midarr         (phoenix_live_view 0.18.17) lib/phoenix_live_view/diff.ex:396: Phoenix.LiveView.Diff.traverse/7
```

**Comment by trueChazza** [comment]
- **New mount paths.** https://github.com/midarrlabs/midarr-server/blob/v3.0.0-beta.2/README.md?plain=1#L84,L85
- **Original issue**. https://github.com/midarrlabs/midarr-server/issues/268

Hi @onedr0p

Sorry about that - yes this is a breaking change in `v3.0.0` Midarr now looks explicitly in `/movies` and `/series` for your media.

So your docker-compose would be:
```yaml
  midarr:
    container_name: midarr
    image: ghcr.io/midarrlabs/midarr-server:v3.0.0-beta.2
    ports:
      - 4000:4000
    volumes:
      - /eros/Media:/movies:ro
      - /eros/Media:/series:ro

  radarr:
    container_name: radarr
    image: linuxserver/radarr:version-4.1.0.6175
    ports:
      - 7878:7878
    volumes:
      - /eros/Media:/media

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:version-3.0.9.1549
    ports:
      - 8989:8989
    volumes:
      - /eros/Media:/media
```
Going by your Midarr volume mounts - I'm assuming your movies and series are at the root of `/eros/Media`?
I've realised this would mean mounting it twice, to cover both movie and series directories (which is not ideal).

**Comment by onedr0p** [comment]
I was hoping to avoid mounting this volume twice 😕

**Comment by trueChazza** [comment]
Just an idea - say I added a 3rd mount directory for situations like yours, where all your media is at the root?

So the volume mount options would be:

```yaml
  midarr:
    container_name: midarr
    image: ghcr.io/midarrlabs/midarr-server:latest
    ports:
      - 4000:4000
    volumes:
#       Media paths
      - /path/to/movies:/movies
      - /path/to/series:/series
      - /path/to/media:/media # for root directory media
```

So both scenarios would be covered. What do you think?
