### ISSUE TITLE
Postgresql - dependency failed to start 

### ISSUE THREAD

**Issue by Tataukee** [midarrlabs/midarr-server#404]
Trying to install the app from Portainer following the exact docker compose unfortunately i am not getting thru .
is there any inputs I have to remove / add / correct ?
any help is very appreciative  

volumes:
  database-data:

services:
  
  midarr:
    container_name: midarr
    image: ghcr.io/midarrlabs/midarr-server:latest
    ports:
      - 4000:4000
    volumes:
      - /volume1/docker/midarr/media:/media
    environment:
#       App config
      - APP_URL=http:my host IP:4000
      - APP_MAILER_FROM=example@email.com
      - SENDGRID_API_KEY=someApiKey

#       Database config
      - DB_USERNAME=my_user
      - DB_PASSWORD=my_password
      - DB_DATABASE=my_database
      - DB_HOSTNAME=postgresql

#       Admin account
      - SETUP_ADMIN_EMAIL=my email 
      - SETUP_ADMIN_NAME=my user
      - SETUP_ADMIN_PASSWORD=my password # minimum length 12

#       Radarr integration
      - RADARR_BASE_URL=my host IP:7878
      - RADARR_API_KEY=API KEY

#       Sonarr integration
      - SONARR_BASE_URL=my host IP:8989
      - SONARR_API_KEY=API KEY

#       OIDC / OAuth 2.0 integration
      - OAUTH_CLIENT_ID=someClientId
      - OAUTH_CLIENT_SECRET=someClientSecret
      - OAUTH_ISSUER_URL=http://some-provider.url
      - OAUTH_AUTHORIZE_URL=http://some-provider.url/authorize
      - OAUTH_TOKEN_URL=http://some-provider.url/token
      - OAUTH_REDIRECT_URI=http://some-provider.url/auth/callback
      - OAUTH_USER_URL=http://some-provider.url/user

    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    container_name: postgresql
    image: postgres
    volumes:
      - /volume1/docker/midarr/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=my_database
    healthcheck:
      test: "exit 0"

**Comment by trueChazza** [comment]
https://github.com/midarrlabs/midarr-server/issues/403#issuecomment-1702681131

Hi! Sorry you've had some issues. Could you try the linked docker compose and see how you go?

**Comment by Tataukee** [comment]
Hello ,
Excellent ! , following the compose you provided it worked like a charm . Thank you so much .
Now, I have two folders ( Movies and Series ) needed to mount . 
Here are the two lines I have added to the compose :

midarr:
    container_name: midarr
    image: ghcr.io/midarrlabs/midarr-server:latest
    ports:
      - 4000:4000
    volumes:
      **- /volume2/Folder II/Media/Movies:/media
      - /volume2/Folder II/Media/TV Shows:/media**
    environment:
   ...etc 

1- I am not able to see the content of both folders .
2- Do you think I should modify the names of the path to small capital letters ? and also are the spacing a problem causing not mounting properly both paths ? 
because my media locations are exactly that path .
Thanks again .

**Comment by trueChazza** [comment]
https://github.com/midarrlabs/midarr-server#why-wont-my-media-play

Did you manage to get this working? I would recommend reading through the FAQ.

**Comment by Tataukee** [comment]
My media root path is set but i dont see any movies/shows within the interface .. I believe midarr don't see the media somehow ..

**Comment by trueChazza** [comment]
Is there media showing in Radarr and Sonarr?

Remember Radarr and Sonarr are responsible for sending your media to Midarr. Your volume mounts are only in Midarr for playback.

**Comment by Tataukee** [comment]
Yes . I have both Radarr and Sonarr handling my search media and they both are sending requests to SABnzbd

**Comment by Tataukee** [comment]
How should midarr integrates with Radarr and Sonarr ?

**Comment by trueChazza** [comment]
> I dont actually understand how Midarr should pick up the media from Radarr or Sonarr , recognise the files and play them ?


```yaml
environment:
      - RADARR_BASE_URL=radarr:7878 # required
      - RADARR_API_KEY=someApiKey # required

      - SONARR_BASE_URL=sonarr:8989 # required
      - SONARR_API_KEY=someApiKey # required
```

Ah no worries, please ensure these environment variables are set. Radarr and Sonarr URLS with their API keys. This allows Midarr to retrieve and show your media library.

You'll find the API keys in `Radarr / Sonarr -> Settings -> General`

**Comment by Tataukee** [comment]
Finally Midarr picked up the files I have currently in the both Movies and Series folders .. and the are showing in Midarr interface . However when I try to play a content , i get an internal server error . Any idea ?

**Comment by trueChazza** [comment]
> However when I try to play a content , i get an internal server error . Any idea ?

https://github.com/midarrlabs/midarr-server#why-wont-my-media-play

Yes so this is where your volume mounts must match in Midarr / Radarr / Sonarr

**Comment by Tataukee** [comment]
I have included both Movies/Series folders volume path in Midarr's docker compose but still not able to play anything .. what am I doing wrong ?

**Comment by Tataukee** [comment]
Yes so this is where your volume mounts must match in Midarr / Radarr / Sonarr
Can you provide an example of a volume match between : Midarr / Radarr / Sonarr ?
some kind of an example of a path to media for Midarr / Radarr / sonarr ??

**Comment by trueChazza** [comment]
```yaml
services:

  midarr:
    volumes:
      - "/volume2/Folder II/Media:/media"

  radarr:
    volumes:
      - "/volume2/Folder II/Media:/media"

  sonarr:
    volumes:
      - "/volume2/Folder II/Media:/media"
```

Based on your [comment](https://github.com/midarrlabs/midarr-server/issues/404#issuecomment-1712955735) try mounting your top level "Media" folder in all 3. Then in Radarr and Sonarr setup your "Root Folders" to "Movies" and "TV Shows".

**Comment by Tataukee** [comment]
The problem with this setup as you mentioned , when I integrate these 3 volumes under services in the docker compose ( regardless the mounting path ), it comes back with an error when i try to update : Failed to deploy a Stack service "sonarr" ; "radarr" has neither an image nor a build context specified : invalid compose project .
![Sonarr](https://github.com/midarrlabs/midarr-server/assets/26170999/51d08b22-7fdd-42ca-bd53-87b363b68758)
![Radarr](https://github.com/midarrlabs/midarr-server/assets/26170999/9dee7d19-8bc2-4e95-bbd2-83b47688e01e)

**Comment by trueChazza** [comment]
Ah I see whats going on, thanks for posting that. 

Radarr and Sonarr need more config than just a volume. The [example](https://github.com/midarrlabs/midarr-server/issues/404#issuecomment-1714732898) I gave omitted everything except the volumes part - I left this for you to fill in with your own.

I would highly recommend you check out the [Docker Compose docs](https://docs.docker.com/compose/features-uses/) and familiarise yourself with it. It's outside the scope of the project for me to take you through it and explain etc. Plenty of resources out there - as well as just giving it a go.

Take a look through the [local dev docker compose](https://github.com/midarrlabs/midarr-server/blob/master/docker-compose.yml) too, as it will demonstrate how to set a stack up in Docker.

Good luck!

**Comment by trueChazza** [comment]
With your Radarr and Sonarr screenshots - I see your root folders are "/movies" and "/tvshows"

Are the absolute paths something like - `/volume2/Folder II/Media/{movies / tvshows}`?

If so try this (just fill in your Radarr and Sonarr URLs and API keys):

```yaml
version: "3.4"

volumes:
  postgresql-data:

services:

  midarr:
    container_name: midarr
    image: ghcr.io/midarrlabs/midarr-server:latest
    volumes:
      - "/volume2/Folder II/Media/movies:/movies"
      - "/volume2/Folder II/Media/tvshows:/tvshows"
    ports:
      - 4000:4000
    environment:
      - APP_URL=http://midarr:4000

      - DB_USERNAME=my_user
      - DB_PASSWORD=my_password
      - DB_DATABASE=my_database
      - DB_HOSTNAME=postgresql

      - SETUP_ADMIN_EMAIL=admin@email.com
      - SETUP_ADMIN_NAME=admin
      - SETUP_ADMIN_PASSWORD=somepassword

      - RADARR_BASE_URL=radarr:7878 # required
      - RADARR_API_KEY=someApiKey # required

      - SONARR_BASE_URL=sonarr:8989 # required
      - SONARR_API_KEY=someApiKey # required

    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    container_name: postgresql
    image: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=my_database
    healthcheck:
      test: "exit 0"
```
