### ISSUE TITLE
[BUG]: Can't start with docker-compose.yaml

### ISSUE THREAD

**Issue by Jipok** [midarrlabs/midarr-server#478]
My docker-compose.yaml:
```yaml
services:

  midarr:
    container_name: midarr
    image: ghcr.io/midarrlabs/midarr-server:latest
    ports:
      - 127.0.0.1:8092:4000
    volumes:
      - /mainpool/trnt:/media
    environment:
#       App config
      - APP_URL=http://midarr:8092

#       Database config
      - DB_USERNAME=my_user
      - DB_PASSWORD=my_password
      - DB_DATABASE=my_database
      - DB_HOSTNAME=postgresql

#       Admin account
      - SETUP_ADMIN_EMAIL=admin@email.com
      - SETUP_ADMIN_NAME=admin
      - SETUP_ADMIN_PASSWORD=somepassword # minimum length 12

#       Radarr integration
#      - RADARR_BASE_URL=radarr:7878
#      - RADARR_API_KEY=someApiKey

#       Sonarr integration
#      - SONARR_BASE_URL=sonarr:8989
#      - SONARR_API_KEY=someApiKey

    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    container_name: postgresql
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=my_database
    healthcheck:
      test: "exit 0"
```
Error on `podman-compose up`:
```
psql: error: connection to server on socket "/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
...
[midarr]     | 20:26:04.079 [notice] Application media_server exited: MediaServer.Application.start(:normal, []) returned an error: shutdown: failed to start child: MediaServer.MoviesIndex
[midarr]     |     ** (EXIT) an exception was raised:
[midarr]     |         ** (FunctionClauseError) no function clause matching in String.valid?/2
[midarr]     |             (elixir 1.15.7) lib/string.ex:1827: String.valid?(nil, :default)
[midarr]     |             (media_server 4.2.0) lib/media_server_web/repositories/movies.ex:3: MediaServerWeb.Repositories.Movies.get/1
[midarr]     |             (media_server 4.2.0) lib/media_server_web/repositories/movies.ex:22: MediaServerWeb.Repositories.Movies.get_all/0
[midarr]     |             (elixir 1.15.7) lib/agent/server.ex:8: Agent.Server.init/1
[midarr]     |             (stdlib 3.17.2.4) gen_server.erl:423: :gen_server.init_it/2
[midarr]     |             (stdlib 3.17.2.4) gen_server.erl:390: :gen_server.init_it/6
[midarr]     |             (stdlib 3.17.2.4) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
[midarr]     | {"Kernel pid terminated",application_controller,"{application_start_failure,media_server,{{shutdown,{failed_to_start_child,'Elixir.MediaServer.MoviesIndex',{function_clause,[{'Elixir.String','valid?',[nil,default],[{file,\"lib/string.ex\"},{line,1827}]},{'Elixir.MediaServerWeb.Repositories.Movies',get,1,[{file,\"lib/media_server_web/repositories/movies.ex\"},{line,3}]},{'Elixir.MediaServerWeb.Repositories.Movies',get_all,0,[{file,\"lib/media_server_web/repositories/movies.ex\"},{line,22}]},{'Elixir.Agent.Server',init,1,[{file,\"lib/agent/server.ex\"},{line,8}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,423}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}},{'Elixir.MediaServer.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,media_server,{{shutdown,{failed_to_start_child,'Elixir.MediaServer.MoviesIndex',{function_clause,[{'Elixir.String','valid?',[nil,default],[{file,"lib/string.ex"},{line,1827}]},{'Elixir.MediaServerWeb.Repositories.Movies',get,1,[{file,"lib/media_server_web/repositories/movies.ex"},{line,3}]},{'Elixir.MediaServerWeb.Repositories.Movies',get_all,0,[{file,"lib/media_server_web/repositories/movies.ex"},{line,22}]},{'Elixir.Agent.Server',init,1,[{file,"lib/agent/server.ex"},{line,8}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.MediaServer.Application',start,[normal,[]]}}})

```
Full log: https://snips.sh/f/vj0aO9FoVJ

Images:
```
REPOSITORY                        TAG           IMAGE ID      CREATED       SIZE
docker.io/machines/filestash      latest-amd64  814d6f95f449  3 weeks ago   1.52 GB
docker.io/library/postgres        latest        d60dc4bd84c0  7 weeks ago   439 MB
ghcr.io/midarrlabs/midarr-server  latest        9d6269f43acf  2 months ago  791 MB
```
